
server.port=${PORT:8090}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


app.jwt.secret=${JWT_SECRET:5lLp/3jhRi3AbIKQ0rhCplk8siYHLic3x7UmxC11qNJBETSuGsRPKJNILVvjznSPIer5bYNc4FEYxZ7hZJt6Ow==}
app.jwt.access-token-expiry=${JWT_ACCESS_EXPIRY:900000}
app.jwt.refresh-token-expiry=${JWT_REFRESH_EXPIRY:604800000}
# 900000ms  = 15 minutes  (access token)
# 604800000ms = 7 days    (refresh token)

# This is used if you configure CORS via properties
# Your SecurityConfig.java already handles CORS so this is optional
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}